<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "msvariants"
 *
 * Auto generated by Extension Builder 2016-05-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Multishop Variants',
	'description' => 'This extension provides variants to multishop products.',
	'category' => 'fe',
	'author' => 'Alfredo A. Villalba Castro',
	'author_email' => 'piramidex@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);